// utils/currencies.js - shared ISO 4217 currency list used by the
// candidate-profile work preferences (expected salary) field.
// `iso` is the lowercase country code used by the `flag-icons` package
// (className `fi fi-${iso}`) - emoji flags don't render as icons on Windows.
const CURRENCIES_RAW = [
  { code: 'AED', name: 'UAE Dirham', iso: 'ae' },
  { code: 'AFN', name: 'Afghan Afghani', iso: 'af' },
  { code: 'ALL', name: 'Albanian Lek', iso: 'al' },
  { code: 'AMD', name: 'Armenian Dram', iso: 'am' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', iso: 'cw' },
  { code: 'AOA', name: 'Angolan Kwanza', iso: 'ao' },
  { code: 'ARS', name: 'Argentine Peso', iso: 'ar' },
  { code: 'AUD', name: 'Australian Dollar', iso: 'au' },
  { code: 'AWG', name: 'Aruban Florin', iso: 'aw' },
  { code: 'AZN', name: 'Azerbaijani Manat', iso: 'az' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', iso: 'ba' },
  { code: 'BBD', name: 'Barbadian Dollar', iso: 'bb' },
  { code: 'BDT', name: 'Bangladeshi Taka', iso: 'bd' },
  { code: 'BGN', name: 'Bulgarian Lev', iso: 'bg' },
  { code: 'BHD', name: 'Bahraini Dinar', iso: 'bh' },
  { code: 'BIF', name: 'Burundian Franc', iso: 'bi' },
  { code: 'BMD', name: 'Bermudan Dollar', iso: 'bm' },
  { code: 'BND', name: 'Brunei Dollar', iso: 'bn' },
  { code: 'BOB', name: 'Bolivian Boliviano', iso: 'bo' },
  { code: 'BRL', name: 'Brazilian Real', iso: 'br' },
  { code: 'BSD', name: 'Bahamian Dollar', iso: 'bs' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', iso: 'bt' },
  { code: 'BWP', name: 'Botswanan Pula', iso: 'bw' },
  { code: 'BYN', name: 'Belarusian Ruble', iso: 'by' },
  { code: 'BZD', name: 'Belize Dollar', iso: 'bz' },
  { code: 'CAD', name: 'Canadian Dollar', iso: 'ca' },
  { code: 'CDF', name: 'Congolese Franc', iso: 'cd' },
  { code: 'CHF', name: 'Swiss Franc', iso: 'ch' },
  { code: 'CLP', name: 'Chilean Peso', iso: 'cl' },
  { code: 'CNY', name: 'Chinese Yuan', iso: 'cn' },
  { code: 'COP', name: 'Colombian Peso', iso: 'co' },
  { code: 'CRC', name: 'Costa Rican Colón', iso: 'cr' },
  { code: 'CUP', name: 'Cuban Peso', iso: 'cu' },
  { code: 'CVE', name: 'Cape Verdean Escudo', iso: 'cv' },
  { code: 'CZK', name: 'Czech Koruna', iso: 'cz' },
  { code: 'DJF', name: 'Djiboutian Franc', iso: 'dj' },
  { code: 'DKK', name: 'Danish Krone', iso: 'dk' },
  { code: 'DOP', name: 'Dominican Peso', iso: 'do' },
  { code: 'DZD', name: 'Algerian Dinar', iso: 'dz' },
  { code: 'EGP', name: 'Egyptian Pound', iso: 'eg' },
  { code: 'ERN', name: 'Eritrean Nakfa', iso: 'er' },
  { code: 'ETB', name: 'Ethiopian Birr', iso: 'et' },
  { code: 'EUR', name: 'Euro', iso: 'eu' },
  { code: 'FJD', name: 'Fijian Dollar', iso: 'fj' },
  { code: 'FKP', name: 'Falkland Islands Pound', iso: 'fk' },
  { code: 'GBP', name: 'British Pound Sterling', iso: 'gb' },
  { code: 'GEL', name: 'Georgian Lari', iso: 'ge' },
  { code: 'GHS', name: 'Ghanaian Cedi', iso: 'gh' },
  { code: 'GIP', name: 'Gibraltar Pound', iso: 'gi' },
  { code: 'GMD', name: 'Gambian Dalasi', iso: 'gm' },
  { code: 'GNF', name: 'Guinean Franc', iso: 'gn' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', iso: 'gt' },
  { code: 'GYD', name: 'Guyanaese Dollar', iso: 'gy' },
  { code: 'HKD', name: 'Hong Kong Dollar', iso: 'hk' },
  { code: 'HNL', name: 'Honduran Lempira', iso: 'hn' },
  { code: 'HRK', name: 'Croatian Kuna', iso: 'hr' },
  { code: 'HTG', name: 'Haitian Gourde', iso: 'ht' },
  { code: 'HUF', name: 'Hungarian Forint', iso: 'hu' },
  { code: 'IDR', name: 'Indonesian Rupiah', iso: 'id' },
  { code: 'ILS', name: 'Israeli New Shekel', iso: 'il' },
  { code: 'INR', name: 'Indian Rupee', iso: 'in' },
  { code: 'IQD', name: 'Iraqi Dinar', iso: 'iq' },
  { code: 'IRR', name: 'Iranian Rial', iso: 'ir' },
  { code: 'ISK', name: 'Icelandic Króna', iso: 'is' },
  { code: 'JMD', name: 'Jamaican Dollar', iso: 'jm' },
  { code: 'JOD', name: 'Jordanian Dinar', iso: 'jo' },
  { code: 'JPY', name: 'Japanese Yen', iso: 'jp' },
  { code: 'KES', name: 'Kenyan Shilling', iso: 'ke' },
  { code: 'KGS', name: 'Kyrgystani Som', iso: 'kg' },
  { code: 'KHR', name: 'Cambodian Riel', iso: 'kh' },
  { code: 'KMF', name: 'Comorian Franc', iso: 'km' },
  { code: 'KRW', name: 'South Korean Won', iso: 'kr' },
  { code: 'KWD', name: 'Kuwaiti Dinar', iso: 'kw' },
  { code: 'KYD', name: 'Cayman Islands Dollar', iso: 'ky' },
  { code: 'KZT', name: 'Kazakhstani Tenge', iso: 'kz' },
  { code: 'LAK', name: 'Laotian Kip', iso: 'la' },
  { code: 'LBP', name: 'Lebanese Pound', iso: 'lb' },
  { code: 'LKR', name: 'Sri Lankan Rupee', iso: 'lk' },
  { code: 'LRD', name: 'Liberian Dollar', iso: 'lr' },
  { code: 'LSL', name: 'Lesotho Loti', iso: 'ls' },
  { code: 'LYD', name: 'Libyan Dinar', iso: 'ly' },
  { code: 'MAD', name: 'Moroccan Dirham', iso: 'ma' },
  { code: 'MDL', name: 'Moldovan Leu', iso: 'md' },
  { code: 'MGA', name: 'Malagasy Ariary', iso: 'mg' },
  { code: 'MKD', name: 'Macedonian Denar', iso: 'mk' },
  { code: 'MMK', name: 'Myanmar Kyat', iso: 'mm' },
  { code: 'MNT', name: 'Mongolian Tugrik', iso: 'mn' },
  { code: 'MOP', name: 'Macanese Pataca', iso: 'mo' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', iso: 'mr' },
  { code: 'MUR', name: 'Mauritian Rupee', iso: 'mu' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', iso: 'mv' },
  { code: 'MWK', name: 'Malawian Kwacha', iso: 'mw' },
  { code: 'MXN', name: 'Mexican Peso', iso: 'mx' },
  { code: 'MYR', name: 'Malaysian Ringgit', iso: 'my' },
  { code: 'MZN', name: 'Mozambican Metical', iso: 'mz' },
  { code: 'NAD', name: 'Namibian Dollar', iso: 'na' },
  { code: 'NGN', name: 'Nigerian Naira', iso: 'ng' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', iso: 'ni' },
  { code: 'NOK', name: 'Norwegian Krone', iso: 'no' },
  { code: 'NPR', name: 'Nepalese Rupee', iso: 'np' },
  { code: 'NZD', name: 'New Zealand Dollar', iso: 'nz' },
  { code: 'OMR', name: 'Omani Rial', iso: 'om' },
  { code: 'PAB', name: 'Panamanian Balboa', iso: 'pa' },
  { code: 'PEN', name: 'Peruvian Sol', iso: 'pe' },
  { code: 'PGK', name: 'Papua New Guinean Kina', iso: 'pg' },
  { code: 'PHP', name: 'Philippine Peso', iso: 'ph' },
  { code: 'PKR', name: 'Pakistani Rupee', iso: 'pk' },
  { code: 'PLN', name: 'Polish Zloty', iso: 'pl' },
  { code: 'PYG', name: 'Paraguayan Guarani', iso: 'py' },
  { code: 'QAR', name: 'Qatari Rial', iso: 'qa' },
  { code: 'RON', name: 'Romanian Leu', iso: 'ro' },
  { code: 'RSD', name: 'Serbian Dinar', iso: 'rs' },
  { code: 'RUB', name: 'Russian Ruble', iso: 'ru' },
  { code: 'RWF', name: 'Rwandan Franc', iso: 'rw' },
  { code: 'SAR', name: 'Saudi Riyal', iso: 'sa' },
  { code: 'SBD', name: 'Solomon Islands Dollar', iso: 'sb' },
  { code: 'SCR', name: 'Seychellois Rupee', iso: 'sc' },
  { code: 'SDG', name: 'Sudanese Pound', iso: 'sd' },
  { code: 'SEK', name: 'Swedish Krona', iso: 'se' },
  { code: 'SGD', name: 'Singapore Dollar', iso: 'sg' },
  { code: 'SHP', name: 'Saint Helena Pound', iso: 'sh' },
  { code: 'SLE', name: 'Sierra Leonean Leone', iso: 'sl' },
  { code: 'SOS', name: 'Somali Shilling', iso: 'so' },
  { code: 'SRD', name: 'Surinamese Dollar', iso: 'sr' },
  { code: 'SSP', name: 'South Sudanese Pound', iso: 'ss' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', iso: 'st' },
  { code: 'SYP', name: 'Syrian Pound', iso: 'sy' },
  { code: 'SZL', name: 'Swazi Lilangeni', iso: 'sz' },
  { code: 'THB', name: 'Thai Baht', iso: 'th' },
  { code: 'TJS', name: 'Tajikistani Somoni', iso: 'tj' },
  { code: 'TMT', name: 'Turkmenistani Manat', iso: 'tm' },
  { code: 'TND', name: 'Tunisian Dinar', iso: 'tn' },
  { code: 'TOP', name: 'Tongan Paʻanga', iso: 'to' },
  { code: 'TRY', name: 'Turkish Lira', iso: 'tr' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', iso: 'tt' },
  { code: 'TWD', name: 'New Taiwan Dollar', iso: 'tw' },
  { code: 'TZS', name: 'Tanzanian Shilling', iso: 'tz' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', iso: 'ua' },
  { code: 'UGX', name: 'Ugandan Shilling', iso: 'ug' },
  { code: 'USD', name: 'US Dollar', iso: 'us' },
  { code: 'UYU', name: 'Uruguayan Peso', iso: 'uy' },
  { code: 'UZS', name: 'Uzbekistani Som', iso: 'uz' },
  { code: 'VES', name: 'Venezuelan Bolívar', iso: 've' },
  { code: 'VND', name: 'Vietnamese Dong', iso: 'vn' },
  { code: 'VUV', name: 'Vanuatu Vatu', iso: 'vu' },
  { code: 'WST', name: 'Samoan Tala', iso: 'ws' },
  { code: 'XAF', name: 'Central African CFA Franc', iso: 'un' },
  { code: 'XCD', name: 'East Caribbean Dollar', iso: 'un' },
  { code: 'XOF', name: 'West African CFA Franc', iso: 'un' },
  { code: 'XPF', name: 'CFP Franc', iso: 'pf' },
  { code: 'YER', name: 'Yemeni Rial', iso: 'ye' },
  { code: 'ZAR', name: 'South African Rand', iso: 'za' },
  { code: 'ZMW', name: 'Zambian Kwacha', iso: 'zm' },
];

// Default/most-used currencies shown first in the picker, in this fixed order.
export const MOST_USED_CURRENCY_CODES = ['EUR', 'USD', 'GBP', 'CNY', 'RUB'];

export const CURRENCIES = CURRENCIES_RAW.slice().sort((a, b) => a.code.localeCompare(b.code));
export const CURRENCY_MAP = Object.fromEntries(CURRENCIES.map((c) => [c.code, c]));

export const MOST_USED_CURRENCIES = MOST_USED_CURRENCY_CODES.map((code) => CURRENCY_MAP[code]).filter(Boolean);
export const OTHER_CURRENCIES = CURRENCIES.filter((c) => !MOST_USED_CURRENCY_CODES.includes(c.code));

export const CURRENCY_CODES = CURRENCIES.map((c) => c.code);
