// Normalized skill catalog: every entry carries a category and any common
// alternate spellings, so free-text input (profile edit) and search filters
// both resolve to one canonical name - mirrors the certifications.js /
// industries.js pattern. This stays frontend-only for now; once a backend
// exists, SKILL_CATALOG maps directly onto a Skill/SkillAlias table pair.
//
// A handful of names (Realm, Snowflake, Rust, Ubuntu, GraphQL, gRPC,
// Postman, REST API, Apache Airflow) legitimately belong to more than one
// category, so they appear as separate entries under each - the catalog has
// no multi-category field, so this is the cheapest way to make them show up
// in every relevant category filter without collapsing categories together.
export const SKILL_CATALOG = [
  // Frontend
  { category: 'Frontend', name: 'HTML' },
  { category: 'Frontend', name: 'CSS' },
  { category: 'Frontend', name: 'SCSS', aliases: ['SASS'] },
  { category: 'Frontend', name: 'Less' },
  { category: 'Frontend', name: 'JavaScript', aliases: ['JS'] },
  { category: 'Frontend', name: 'TypeScript', aliases: ['TS'] },
  { category: 'Frontend', name: 'React', aliases: ['ReactJS', 'React.js'] },
  { category: 'Frontend', name: 'Next.js', aliases: ['NextJS'] },
  { category: 'Frontend', name: 'Vue.js', aliases: ['VueJS', 'Vue'] },
  { category: 'Frontend', name: 'Nuxt.js', aliases: ['NuxtJS'] },
  { category: 'Frontend', name: 'Angular' },
  { category: 'Frontend', name: 'Svelte' },
  { category: 'Frontend', name: 'SolidJS' },
  { category: 'Frontend', name: 'Astro' },
  { category: 'Frontend', name: 'Remix' },
  { category: 'Frontend', name: 'Gatsby' },
  { category: 'Frontend', name: 'Qwik' },
  { category: 'Frontend', name: 'Alpine.js' },
  { category: 'Frontend', name: 'Lit' },
  { category: 'Frontend', name: 'Stencil' },
  { category: 'Frontend', name: 'Redux', aliases: ['Redux Toolkit'] },
  { category: 'Frontend', name: 'MobX' },
  { category: 'Frontend', name: 'Zustand' },
  { category: 'Frontend', name: 'React Query', aliases: ['TanStack Query'] },
  { category: 'Frontend', name: 'GraphQL' },
  { category: 'Frontend', name: 'Apollo' },
  { category: 'Frontend', name: 'Relay' },
  { category: 'Frontend', name: 'Emotion' },
  { category: 'Frontend', name: 'Styled Components' },
  { category: 'Frontend', name: 'CSS Modules' },
  { category: 'Frontend', name: 'React Hook Form' },
  { category: 'Frontend', name: 'Formik' },
  { category: 'Frontend', name: 'Yup' },
  { category: 'Frontend', name: 'Zod' },
  { category: 'Frontend', name: 'Axios' },
  { category: 'Frontend', name: 'SWR' },
  { category: 'Frontend', name: 'RxJS' },
  { category: 'Frontend', name: 'i18next' },
  { category: 'Frontend', name: 'React Router' },
  { category: 'Frontend', name: 'TanStack Router' },
  { category: 'Frontend', name: 'Webpack' },
  { category: 'Frontend', name: 'Vite' },
  { category: 'Frontend', name: 'Parcel' },
  { category: 'Frontend', name: 'Rollup' },
  { category: 'Frontend', name: 'Babel' },
  { category: 'Frontend', name: 'ESLint' },
  { category: 'Frontend', name: 'Prettier' },
  { category: 'Frontend', name: 'Jest' },
  { category: 'Frontend', name: 'Vitest' },
  { category: 'Frontend', name: 'React Testing Library' },
  { category: 'Frontend', name: 'MSW' },
  { category: 'Frontend', name: 'Storybook' },
  { category: 'Frontend', name: 'Tailwind CSS', aliases: ['Tailwind'] },
  { category: 'Frontend', name: 'Bootstrap' },
  { category: 'Frontend', name: 'Material UI', aliases: ['MUI'] },
  { category: 'Frontend', name: 'Chakra UI' },
  { category: 'Frontend', name: 'Ant Design' },
  { category: 'Frontend', name: 'Framer Motion' },
  { category: 'Frontend', name: 'Three.js', aliases: ['ThreeJS'] },
  { category: 'Frontend', name: 'D3.js', aliases: ['D3'] },

  // Backend
  { category: 'Backend', name: 'Node.js', aliases: ['Node', 'NodeJS'] },
  { category: 'Backend', name: 'Express', aliases: ['Express.js'] },
  { category: 'Backend', name: 'NestJS' },
  { category: 'Backend', name: 'Koa' },
  { category: 'Backend', name: 'Hapi' },
  { category: 'Backend', name: 'tRPC' },
  { category: 'Backend', name: 'Prisma' },
  { category: 'Backend', name: 'TypeORM' },
  { category: 'Backend', name: 'Sequelize' },
  { category: 'Backend', name: 'Drizzle ORM' },
  { category: 'Backend', name: 'MikroORM' },
  { category: 'Backend', name: 'Java' },
  { category: 'Backend', name: 'Spring', aliases: ['Spring Boot'] },
  { category: 'Backend', name: 'Hibernate' },
  { category: 'Backend', name: 'Quarkus' },
  { category: 'Backend', name: 'Micronaut' },
  { category: 'Backend', name: 'Vert.x' },
  { category: 'Backend', name: 'Akka' },
  { category: 'Backend', name: 'Kotlin' },
  { category: 'Backend', name: 'Python' },
  { category: 'Backend', name: 'Django' },
  { category: 'Backend', name: 'Flask' },
  { category: 'Backend', name: 'FastAPI' },
  { category: 'Backend', name: 'Celery' },
  { category: 'Backend', name: 'PHP' },
  { category: 'Backend', name: 'Laravel' },
  { category: 'Backend', name: 'Symfony' },
  { category: 'Backend', name: 'C#' },
  { category: 'Backend', name: '.NET', aliases: ['ASP.NET', 'dotnet'] },
  { category: 'Backend', name: 'Go', aliases: ['Golang'] },
  { category: 'Backend', name: 'Gin' },
  { category: 'Backend', name: 'Fiber' },
  { category: 'Backend', name: 'Echo' },
  { category: 'Backend', name: 'Rust' },
  { category: 'Backend', name: 'Actix' },
  { category: 'Backend', name: 'Rocket' },
  { category: 'Backend', name: 'Tokio' },
  { category: 'Backend', name: 'Ruby' },
  { category: 'Backend', name: 'Ruby on Rails', aliases: ['Rails'] },
  { category: 'Backend', name: 'Scala' },
  { category: 'Backend', name: 'Elixir', aliases: ['Phoenix'] },
  { category: 'Backend', name: 'REST API' },
  { category: 'Backend', name: 'gRPC' },
  { category: 'Backend', name: 'Microservices' },
  { category: 'Backend', name: 'RabbitMQ' },
  { category: 'Backend', name: 'Apache Kafka' },
  { category: 'Backend', name: 'NATS' },
  { category: 'Backend', name: 'ZeroMQ' },

  // Database
  { category: 'Database', name: 'SQL' },
  { category: 'Database', name: 'MySQL' },
  { category: 'Database', name: 'PostgreSQL', aliases: ['Postgres'] },
  { category: 'Database', name: 'MariaDB' },
  { category: 'Database', name: 'SQLite' },
  { category: 'Database', name: 'Oracle Database', aliases: ['Oracle'] },
  { category: 'Database', name: 'Microsoft SQL Server', aliases: ['MSSQL', 'SQL Server'] },
  { category: 'Database', name: 'CockroachDB' },
  { category: 'Database', name: 'TimescaleDB' },
  { category: 'Database', name: 'InfluxDB' },
  { category: 'Database', name: 'ClickHouse' },
  { category: 'Database', name: 'MongoDB' },
  { category: 'Database', name: 'ElasticSearch' },
  { category: 'Database', name: 'OpenSearch' },
  { category: 'Database', name: 'CouchDB' },
  { category: 'Database', name: 'Redis' },
  { category: 'Database', name: 'Cassandra' },
  { category: 'Database', name: 'DynamoDB' },
  { category: 'Database', name: 'Neo4j' },
  { category: 'Database', name: 'Realm' },
  { category: 'Database', name: 'FaunaDB' },
  { category: 'Database', name: 'PlanetScale' },
  { category: 'Database', name: 'Snowflake' },
  { category: 'Database', name: 'BigQuery' },
  { category: 'Database', name: 'Amazon Aurora' },
  { category: 'Database', name: 'Amazon RDS' },
  { category: 'Database', name: 'Firebase', aliases: ['Google Firebase'] },
  { category: 'Database', name: 'Supabase' },

  // Cloud & DevOps
  { category: 'Cloud & DevOps', name: 'AWS', aliases: ['Amazon Web Services'] },
  { category: 'Cloud & DevOps', name: 'Amazon EC2' },
  { category: 'Cloud & DevOps', name: 'Amazon ECS' },
  { category: 'Cloud & DevOps', name: 'Amazon EKS' },
  { category: 'Cloud & DevOps', name: 'AWS Lambda' },
  { category: 'Cloud & DevOps', name: 'AWS S3' },
  { category: 'Cloud & DevOps', name: 'AWS IAM' },
  { category: 'Cloud & DevOps', name: 'AWS CloudFormation' },
  { category: 'Cloud & DevOps', name: 'AWS CDK' },
  { category: 'Cloud & DevOps', name: 'Azure', aliases: ['Microsoft Azure'] },
  { category: 'Cloud & DevOps', name: 'Azure Functions' },
  { category: 'Cloud & DevOps', name: 'Azure Kubernetes Service' },
  { category: 'Cloud & DevOps', name: 'Azure Storage' },
  { category: 'Cloud & DevOps', name: 'Google Cloud', aliases: ['GCP'] },
  { category: 'Cloud & DevOps', name: 'Google Kubernetes Engine' },
  { category: 'Cloud & DevOps', name: 'Google Cloud Run' },
  { category: 'Cloud & DevOps', name: 'Oracle Cloud' },
  { category: 'Cloud & DevOps', name: 'IBM Cloud' },
  { category: 'Cloud & DevOps', name: 'Alibaba Cloud' },
  { category: 'Cloud & DevOps', name: 'Huawei Cloud' },
  { category: 'Cloud & DevOps', name: 'Cloudflare' },
  { category: 'Cloud & DevOps', name: 'DigitalOcean' },
  { category: 'Cloud & DevOps', name: 'Heroku' },
  { category: 'Cloud & DevOps', name: 'Vercel' },
  { category: 'Cloud & DevOps', name: 'Netlify' },
  { category: 'Cloud & DevOps', name: 'Render' },
  { category: 'Cloud & DevOps', name: 'Fly.io' },
  { category: 'Cloud & DevOps', name: 'Railway' },
  { category: 'Cloud & DevOps', name: 'OpenShift' },
  { category: 'Cloud & DevOps', name: 'Docker' },
  { category: 'Cloud & DevOps', name: 'Docker Compose' },
  { category: 'Cloud & DevOps', name: 'Podman' },
  { category: 'Cloud & DevOps', name: 'LXC' },
  { category: 'Cloud & DevOps', name: 'Kubernetes', aliases: ['K8s'] },
  { category: 'Cloud & DevOps', name: 'Istio' },
  { category: 'Cloud & DevOps', name: 'Traefik' },
  { category: 'Cloud & DevOps', name: 'Consul' },
  { category: 'Cloud & DevOps', name: 'Vault' },
  { category: 'Cloud & DevOps', name: 'Nomad' },
  { category: 'Cloud & DevOps', name: 'Terraform' },
  { category: 'Cloud & DevOps', name: 'Pulumi' },
  { category: 'Cloud & DevOps', name: 'Packer' },
  { category: 'Cloud & DevOps', name: 'Ansible' },
  { category: 'Cloud & DevOps', name: 'Jenkins' },
  { category: 'Cloud & DevOps', name: 'GitHub Actions' },
  { category: 'Cloud & DevOps', name: 'GitLab CI' },
  { category: 'Cloud & DevOps', name: 'Azure DevOps' },
  { category: 'Cloud & DevOps', name: 'CircleCI' },
  { category: 'Cloud & DevOps', name: 'ArgoCD' },
  { category: 'Cloud & DevOps', name: 'Helm' },
  { category: 'Cloud & DevOps', name: 'OpenTelemetry' },
  { category: 'Cloud & DevOps', name: 'Prometheus' },
  { category: 'Cloud & DevOps', name: 'Grafana' },
  { category: 'Cloud & DevOps', name: 'Fluentd' },
  { category: 'Cloud & DevOps', name: 'Loki' },
  { category: 'Cloud & DevOps', name: 'ELK Stack' },
  { category: 'Cloud & DevOps', name: 'Datadog' },
  { category: 'Cloud & DevOps', name: 'New Relic' },
  { category: 'Cloud & DevOps', name: 'Splunk' },
  { category: 'Cloud & DevOps', name: 'Sentry' },
  { category: 'Cloud & DevOps', name: 'SonarQube' },
  { category: 'Cloud & DevOps', name: 'Trivy' },
  { category: 'Cloud & DevOps', name: 'Harbor' },
  { category: 'Cloud & DevOps', name: 'MinIO' },
  { category: 'Cloud & DevOps', name: 'Nginx' },
  { category: 'Cloud & DevOps', name: 'Apache' },
  { category: 'Cloud & DevOps', name: 'Linux' },
  { category: 'Cloud & DevOps', name: 'Ubuntu' },
  { category: 'Cloud & DevOps', name: 'Bash' },
  { category: 'Cloud & DevOps', name: 'PowerShell' },

  // AI & Data
  { category: 'AI & Data', name: 'MCP' },
  { category: 'AI & Data', name: 'OpenAI API' },
  { category: 'AI & Data', name: 'OpenAI Agents SDK' },
  { category: 'AI & Data', name: 'Claude API', aliases: ['Anthropic API'] },
  { category: 'AI & Data', name: 'Anthropic SDK' },
  { category: 'AI & Data', name: 'Gemini API' },
  { category: 'AI & Data', name: 'Google AI Studio' },
  { category: 'AI & Data', name: 'Vertex AI' },
  { category: 'AI & Data', name: 'Amazon Bedrock' },
  { category: 'AI & Data', name: 'Azure OpenAI' },
  { category: 'AI & Data', name: 'Ollama' },
  { category: 'AI & Data', name: 'vLLM' },
  { category: 'AI & Data', name: 'LM Studio' },
  { category: 'AI & Data', name: 'LangChain' },
  { category: 'AI & Data', name: 'LangGraph' },
  { category: 'AI & Data', name: 'LlamaIndex' },
  { category: 'AI & Data', name: 'Haystack' },
  { category: 'AI & Data', name: 'DSPy' },
  { category: 'AI & Data', name: 'AutoGen' },
  { category: 'AI & Data', name: 'CrewAI' },
  { category: 'AI & Data', name: 'Hugging Face' },
  { category: 'AI & Data', name: 'TensorFlow' },
  { category: 'AI & Data', name: 'PyTorch' },
  { category: 'AI & Data', name: 'Scikit-learn' },
  { category: 'AI & Data', name: 'Pandas' },
  { category: 'AI & Data', name: 'NumPy' },
  { category: 'AI & Data', name: 'Whisper' },
  { category: 'AI & Data', name: 'Stable Diffusion' },
  { category: 'AI & Data', name: 'Diffusers' },
  { category: 'AI & Data', name: 'ONNX' },
  { category: 'AI & Data', name: 'OpenCV' },
  { category: 'AI & Data', name: 'spaCy' },
  { category: 'AI & Data', name: 'NLTK' },
  { category: 'AI & Data', name: 'MLflow' },
  { category: 'AI & Data', name: 'Kubeflow' },
  { category: 'AI & Data', name: 'Apache Airflow' },
  { category: 'AI & Data', name: 'Computer Vision' },
  { category: 'AI & Data', name: 'Machine Learning', aliases: ['ML'] },
  { category: 'AI & Data', name: 'Deep Learning' },
  { category: 'AI & Data', name: 'LLMs' },
  { category: 'AI & Data', name: 'RAG' },
  { category: 'AI & Data', name: 'Vector Databases' },
  { category: 'AI & Data', name: 'Pinecone' },
  { category: 'AI & Data', name: 'Weaviate' },
  { category: 'AI & Data', name: 'ChromaDB' },
  { category: 'AI & Data', name: 'Milvus' },
  { category: 'AI & Data', name: 'Qdrant' },
  { category: 'AI & Data', name: 'FAISS' },
  { category: 'AI & Data', name: 'pgvector' },

  // Mobile
  { category: 'Mobile', name: 'Android' },
  { category: 'Mobile', name: 'iOS' },
  { category: 'Mobile', name: 'Swift' },
  { category: 'Mobile', name: 'SwiftUI' },
  { category: 'Mobile', name: 'Objective-C' },
  { category: 'Mobile', name: 'Flutter' },
  { category: 'Mobile', name: 'Dart' },
  { category: 'Mobile', name: 'React Native' },
  { category: 'Mobile', name: 'Expo' },
  { category: 'Mobile', name: 'Jetpack Compose' },
  { category: 'Mobile', name: 'Xamarin' },
  { category: 'Mobile', name: 'MAUI' },
  { category: 'Mobile', name: 'Capacitor' },
  { category: 'Mobile', name: 'Cordova' },
  { category: 'Mobile', name: 'Ionic' },
  { category: 'Mobile', name: 'NativeScript' },
  { category: 'Mobile', name: 'Realm' },
  { category: 'Mobile', name: 'Firebase Cloud Messaging' },

  // Testing
  { category: 'Testing', name: 'Cypress' },
  { category: 'Testing', name: 'Playwright' },
  { category: 'Testing', name: 'Selenium' },
  { category: 'Testing', name: 'Mocha' },
  { category: 'Testing', name: 'Chai' },
  { category: 'Testing', name: 'Karma' },
  { category: 'Testing', name: 'Jasmine' },
  { category: 'Testing', name: 'JUnit' },
  { category: 'Testing', name: 'NUnit' },
  { category: 'Testing', name: 'TestNG' },
  { category: 'Testing', name: 'Mockito' },
  { category: 'Testing', name: 'WireMock' },
  { category: 'Testing', name: 'Pact' },
  { category: 'Testing', name: 'PyTest' },
  { category: 'Testing', name: 'Postman' },
  { category: 'Testing', name: 'Insomnia' },
  { category: 'Testing', name: 'k6' },
  { category: 'Testing', name: 'JMeter' },
  { category: 'Testing', name: 'Locust' },
  { category: 'Testing', name: 'OWASP ZAP' },
  { category: 'Testing', name: 'Burp Suite' },

  // Design
  { category: 'Design', name: 'Figma' },
  { category: 'Design', name: 'Sketch' },
  { category: 'Design', name: 'Adobe XD' },
  { category: 'Design', name: 'Photoshop' },
  { category: 'Design', name: 'Illustrator' },
  { category: 'Design', name: 'After Effects' },
  { category: 'Design', name: 'Premiere Pro' },
  { category: 'Design', name: 'Blender' },
  { category: 'Design', name: 'Prototyping' },
  { category: 'Design', name: 'User Research' },
  { category: 'Design', name: 'Wireframing' },
  { category: 'Design', name: 'Design Systems' },
  { category: 'Design', name: 'Usability Testing' },
  { category: 'Design', name: 'Accessibility' },

  // Version Control
  { category: 'Version Control', name: 'Git' },
  { category: 'Version Control', name: 'GitHub' },
  { category: 'Version Control', name: 'GitLab' },
  { category: 'Version Control', name: 'Bitbucket' },
  { category: 'Version Control', name: 'SVN' },
  { category: 'Version Control', name: 'Mercurial' },

  // Methodology & Management
  { category: 'Methodology & Management', name: 'Agile' },
  { category: 'Methodology & Management', name: 'Scrum' },
  { category: 'Methodology & Management', name: 'Kanban' },
  { category: 'Methodology & Management', name: 'SAFe' },
  { category: 'Methodology & Management', name: 'Lean' },
  { category: 'Methodology & Management', name: 'DevOps' },
  { category: 'Methodology & Management', name: 'CI/CD' },
  { category: 'Methodology & Management', name: 'TDD' },
  { category: 'Methodology & Management', name: 'BDD' },
  { category: 'Methodology & Management', name: 'DDD' },
  { category: 'Methodology & Management', name: 'Product Strategy' },
  { category: 'Methodology & Management', name: 'Analytics' },

  // ERP & Business
  { category: 'ERP & Business', name: 'SAP' },
  { category: 'ERP & Business', name: 'SAP MM' },
  { category: 'ERP & Business', name: 'SAP FI' },
  { category: 'ERP & Business', name: 'SAP CO' },
  { category: 'ERP & Business', name: 'SAP SD' },
  { category: 'ERP & Business', name: 'SAP HANA' },
  { category: 'ERP & Business', name: 'Oracle ERP' },
  { category: 'ERP & Business', name: 'Microsoft Dynamics' },
  { category: 'ERP & Business', name: 'Salesforce' },
  { category: 'ERP & Business', name: 'HubSpot' },
  { category: 'ERP & Business', name: 'ServiceNow' },
  { category: 'ERP & Business', name: 'Jira' },
  { category: 'ERP & Business', name: 'Confluence' },
  { category: 'ERP & Business', name: 'Slack' },
  { category: 'ERP & Business', name: 'Notion' },
  { category: 'ERP & Business', name: 'Trello' },
  { category: 'ERP & Business', name: 'Asana' },
  { category: 'ERP & Business', name: 'Monday.com' },

  // Security
  { category: 'Security', name: 'OAuth' },
  { category: 'Security', name: 'OAuth2' },
  { category: 'Security', name: 'OIDC' },
  { category: 'Security', name: 'JWT' },
  { category: 'Security', name: 'SAML' },
  { category: 'Security', name: 'LDAP' },
  { category: 'Security', name: 'Keycloak' },
  { category: 'Security', name: 'Okta' },
  { category: 'Security', name: 'Auth0' },
  { category: 'Security', name: 'OWASP' },
  { category: 'Security', name: 'SSL/TLS' },
  { category: 'Security', name: 'PKI' },
  { category: 'Security', name: 'IAM' },
  { category: 'Security', name: 'Penetration Testing' },
  { category: 'Security', name: 'Web Security' },
  { category: 'Security', name: 'Network Security' },
  { category: 'Security', name: 'Application Security' },
  { category: 'Security', name: 'Cybersecurity' },

  // Data Engineering
  { category: 'Data Engineering', name: 'Apache Spark' },
  { category: 'Data Engineering', name: 'Apache Flink' },
  { category: 'Data Engineering', name: 'Apache Beam' },
  { category: 'Data Engineering', name: 'Apache Airflow', aliases: ['Airflow'] },
  { category: 'Data Engineering', name: 'dbt' },
  { category: 'Data Engineering', name: 'Kafka Streams' },
  { category: 'Data Engineering', name: 'Snowflake' },
  { category: 'Data Engineering', name: 'Delta Lake' },
  { category: 'Data Engineering', name: 'Databricks' },
  { category: 'Data Engineering', name: 'Hadoop' },
  { category: 'Data Engineering', name: 'Hive' },
  { category: 'Data Engineering', name: 'Presto' },
  { category: 'Data Engineering', name: 'Trino' },
  { category: 'Data Engineering', name: 'ETL' },
  { category: 'Data Engineering', name: 'ELT' },

  // BI & Analytics
  { category: 'BI & Analytics', name: 'Power BI' },
  { category: 'BI & Analytics', name: 'Tableau' },
  { category: 'BI & Analytics', name: 'Looker' },
  { category: 'BI & Analytics', name: 'Metabase' },
  { category: 'BI & Analytics', name: 'Apache Superset' },
  { category: 'BI & Analytics', name: 'Qlik Sense' },
  { category: 'BI & Analytics', name: 'Google Analytics' },
  { category: 'BI & Analytics', name: 'Mixpanel' },
  { category: 'BI & Analytics', name: 'Amplitude' },
  { category: 'BI & Analytics', name: 'Hotjar' },

  // Game Development
  { category: 'Game Development', name: 'Unity' },
  { category: 'Game Development', name: 'Unreal Engine' },
  { category: 'Game Development', name: 'Godot' },
  { category: 'Game Development', name: 'CryEngine' },
  { category: 'Game Development', name: 'Cocos2d' },
  { category: 'Game Development', name: 'GameMaker' },
  { category: 'Game Development', name: 'OpenGL' },
  { category: 'Game Development', name: 'Vulkan' },
  { category: 'Game Development', name: 'DirectX' },

  // Embedded & IoT
  { category: 'Embedded & IoT', name: 'Arduino' },
  { category: 'Embedded & IoT', name: 'ESP32' },
  { category: 'Embedded & IoT', name: 'ESP8266' },
  { category: 'Embedded & IoT', name: 'Raspberry Pi' },
  { category: 'Embedded & IoT', name: 'STM32' },
  { category: 'Embedded & IoT', name: 'AVR' },
  { category: 'Embedded & IoT', name: 'PIC' },
  { category: 'Embedded & IoT', name: 'ARM Cortex' },
  { category: 'Embedded & IoT', name: 'FreeRTOS' },
  { category: 'Embedded & IoT', name: 'Embedded C' },
  { category: 'Embedded & IoT', name: 'MicroPython' },
  { category: 'Embedded & IoT', name: 'MQTT' },
  { category: 'Embedded & IoT', name: 'CAN Bus' },
  { category: 'Embedded & IoT', name: 'Modbus' },
  { category: 'Embedded & IoT', name: 'Bluetooth Low Energy' },
  { category: 'Embedded & IoT', name: 'Zigbee' },
  { category: 'Embedded & IoT', name: 'LoRaWAN' },

  // Blockchain
  { category: 'Blockchain', name: 'Solidity' },
  { category: 'Blockchain', name: 'Ethereum' },
  { category: 'Blockchain', name: 'Hyperledger' },
  { category: 'Blockchain', name: 'Web3.js' },
  { category: 'Blockchain', name: 'Ethers.js' },
  { category: 'Blockchain', name: 'Hardhat' },
  { category: 'Blockchain', name: 'Foundry' },
  { category: 'Blockchain', name: 'Rust' },
  { category: 'Blockchain', name: 'Solana' },
  { category: 'Blockchain', name: 'Polygon' },

  // CMS
  { category: 'CMS', name: 'WordPress' },
  { category: 'CMS', name: 'Drupal' },
  { category: 'CMS', name: 'Joomla' },
  { category: 'CMS', name: 'Strapi' },
  { category: 'CMS', name: 'Contentful' },
  { category: 'CMS', name: 'Sanity' },
  { category: 'CMS', name: 'Directus' },
  { category: 'CMS', name: 'Ghost' },
  { category: 'CMS', name: 'Shopify' },
  { category: 'CMS', name: 'Magento' },
  { category: 'CMS', name: 'WooCommerce' },

  // Operating Systems
  { category: 'Operating Systems', name: 'Windows' },
  { category: 'Operating Systems', name: 'Windows Server' },
  { category: 'Operating Systems', name: 'macOS' },
  { category: 'Operating Systems', name: 'Ubuntu' },
  { category: 'Operating Systems', name: 'Debian' },
  { category: 'Operating Systems', name: 'Fedora' },
  { category: 'Operating Systems', name: 'CentOS' },
  { category: 'Operating Systems', name: 'Red Hat' },
  { category: 'Operating Systems', name: 'Arch Linux' },
  { category: 'Operating Systems', name: 'Kali Linux' },
  { category: 'Operating Systems', name: 'Unix' },

  // Networking
  { category: 'Networking', name: 'TCP/IP' },
  { category: 'Networking', name: 'DNS' },
  { category: 'Networking', name: 'DHCP' },
  { category: 'Networking', name: 'VPN' },
  { category: 'Networking', name: 'Cisco' },
  { category: 'Networking', name: 'MikroTik' },
  { category: 'Networking', name: 'Juniper' },
  { category: 'Networking', name: 'BGP' },
  { category: 'Networking', name: 'OSPF' },
  { category: 'Networking', name: 'Firewall' },
  { category: 'Networking', name: 'Load Balancing' },

  // API
  { category: 'API', name: 'REST API' },
  { category: 'API', name: 'GraphQL' },
  { category: 'API', name: 'gRPC' },
  { category: 'API', name: 'SOAP' },
  { category: 'API', name: 'WebSockets' },
  { category: 'API', name: 'WebRTC' },
  { category: 'API', name: 'OpenAPI' },
  { category: 'API', name: 'Swagger' },
  { category: 'API', name: 'Postman' },
  { category: 'API', name: 'AsyncAPI' },
];

export const CATEGORY_NAMES = [...new Set(SKILL_CATALOG.map((s) => s.category))];
export const SKILL_NAMES = [...new Set(SKILL_CATALOG.map((s) => s.name))];

export function getSkillsFor({ category } = {}) {
  return SKILL_CATALOG.filter((s) => !category || s.category === category);
}

// Multi-category variant used by the search filter, where several
// categories can be checked at once to narrow the skill list.
export function getSkillNamesFor({ categories = [] } = {}) {
  const names = SKILL_CATALOG.filter(
    (s) => categories.length === 0 || categories.includes(s.category)
  ).map((s) => s.name);
  return [...new Set(names)];
}

// Resolves free-typed input (e.g. "react js", "Node") to its canonical
// catalog name via exact name or alias match, case-insensitive. Returns
// null when nothing matches, so callers can fall back to the raw text -
// the point is to de-dupe known variants, not to reject custom skills.
export function resolveSkillName(input) {
  const needle = String(input || '').trim().toLowerCase();
  if (!needle) return null;
  const match = SKILL_CATALOG.find(
    (s) => s.name.toLowerCase() === needle || s.aliases?.some((a) => a.toLowerCase() === needle)
  );
  return match?.name ?? null;
}
